import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import cookieParser from 'cookie-parser';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import { mkdirSync } from 'node:fs';
import authRoutes from './routes/auth.routes.js';
import healthRoutes from './routes/health.routes.js';
import taskRoutes from './routes/task.routes.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import adminRoutes from './routes/admin.routes.js';
import { env } from './config/env.js';
import { errorHandler, notFound } from './middleware/error.js';
export const app = express();
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: false }));
const allowedOrigins = env.CLIENT_ORIGIN.split(',').map((origin) => origin.trim());
app.use(cors({ origin: (origin, callback) => !origin || allowedOrigins.includes(origin) ? callback(null, true) : callback(new Error('Origin is not allowed by CORS')), credentials: true }));
app.use(compression()); app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 250, standardHeaders: true, legacyHeaders: false }));
app.use(express.json({ limit: '1mb' })); app.use(cookieParser());
mkdirSync('uploads', { recursive: true });
app.use('/uploads', express.static('uploads'));
app.use('/api/v1/health', healthRoutes); app.use('/api/v1/auth', authRoutes);
app.use('/api/v1/tasks', taskRoutes); app.use('/api/v1/dashboard', dashboardRoutes);
app.use('/api/v1/admin', adminRoutes);
app.use(notFound); app.use(errorHandler);
